# vim:ft=ansible:
---
- block:
    - name: Install EPEL Repository
      yum:
        name: epel-release
        update_cache: yes
        state: installed
    - name: Install Nginx
      yum: 
        name: "{{ item }}"
        state: installed 
        update_cache: yes
      with_items:
      - nginx
  - name: Copy the NGINX Conf
    copy: src=nginx.conf dest=/etc/nginx/nginx.conf 
  - name: Copy the fecs Conf
    copy: src=fecs.conf dest=/etc/nginx/conf.d/fecs.conf 
  - name: Enable the Service
    command: systemctl enable nginx
  - name: Start the Service
    command: systemctl start nginx
  become: yes
  become_method: sudo
